/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class idk extends javax.swing.JFrame {

    /**
     * Creates new form idk
     */
    public idk() {
        initComponents();
        edit.setEnabled(false);
        edit1.setEnabled(false);
        edit2.setEnabled(false);
        edit3.setEnabled(false);
        edit4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable1 = new javax.swing.JTable();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        calculate = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtable2 = new javax.swing.JTable();
        calculate1 = new javax.swing.JButton();
        reset1 = new javax.swing.JButton();
        delete1 = new javax.swing.JButton();
        add1 = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtable3 = new javax.swing.JTable();
        calculate2 = new javax.swing.JButton();
        reset2 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        add2 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtable4 = new javax.swing.JTable();
        add3 = new javax.swing.JButton();
        delete3 = new javax.swing.JButton();
        reset3 = new javax.swing.JButton();
        calculate3 = new javax.swing.JButton();
        edit3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtable5 = new javax.swing.JTable();
        calculate4 = new javax.swing.JButton();
        reset4 = new javax.swing.JButton();
        delete4 = new javax.swing.JButton();
        add4 = new javax.swing.JButton();
        edit4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        resources = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Population", "Standard quota", "LQ", "Extra resources", "Final apportionment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable1.setGridColor(new java.awt.Color(0, 153, 153));
        jtable1.setShowVerticalLines(true);
        jtable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtable1);
        if (jtable1.getColumnModel().getColumnCount() > 0) {
            jtable1.getColumnModel().getColumn(0).setResizable(false);
            jtable1.getColumnModel().getColumn(1).setResizable(false);
            jtable1.getColumnModel().getColumn(2).setResizable(false);
            jtable1.getColumnModel().getColumn(3).setResizable(false);
            jtable1.getColumnModel().getColumn(4).setResizable(false);
            jtable1.getColumnModel().getColumn(5).setResizable(false);
        }

        add.setText("Add row");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setText("Delete row");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        jTabbedPane1.addTab("Hamilton's method", jPanel1);

        jtable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Population", "Standard quota", "LQ", "Modified quota", "Final apportionment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable2.setGridColor(new java.awt.Color(0, 153, 153));
        jtable2.setShowGrid(true);
        jtable2.setShowHorizontalLines(false);
        jtable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtable2);
        if (jtable2.getColumnModel().getColumnCount() > 0) {
            jtable2.getColumnModel().getColumn(0).setResizable(false);
            jtable2.getColumnModel().getColumn(1).setResizable(false);
            jtable2.getColumnModel().getColumn(2).setResizable(false);
            jtable2.getColumnModel().getColumn(3).setResizable(false);
            jtable2.getColumnModel().getColumn(4).setResizable(false);
            jtable2.getColumnModel().getColumn(5).setResizable(false);
        }

        calculate1.setText("Calculate");
        calculate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate1ActionPerformed(evt);
            }
        });

        reset1.setText("Reset");
        reset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset1ActionPerformed(evt);
            }
        });

        delete1.setText("Delete row");
        delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete1ActionPerformed(evt);
            }
        });

        add1.setText("Add row");
        add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add1ActionPerformed(evt);
            }
        });

        edit1.setText("Edit");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(add1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );

        jTabbedPane1.addTab("Jefferson's method", jPanel2);

        jtable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Population", "Standard quota", "UQ", "Modified quota", "Final apportionment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable3.setGridColor(new java.awt.Color(0, 153, 153));
        jtable3.setShowVerticalLines(true);
        jtable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtable3);
        if (jtable3.getColumnModel().getColumnCount() > 0) {
            jtable3.getColumnModel().getColumn(0).setResizable(false);
            jtable3.getColumnModel().getColumn(1).setResizable(false);
            jtable3.getColumnModel().getColumn(2).setResizable(false);
            jtable3.getColumnModel().getColumn(3).setResizable(false);
            jtable3.getColumnModel().getColumn(4).setResizable(false);
            jtable3.getColumnModel().getColumn(5).setResizable(false);
        }

        calculate2.setText("Calculate");
        calculate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate2ActionPerformed(evt);
            }
        });

        reset2.setText("Reset");
        reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset2ActionPerformed(evt);
            }
        });

        delete2.setText("Delete row");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });

        add2.setText("Add row");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        edit2.setText("Edit");
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(add2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );

        jTabbedPane1.addTab("Adam's method", jPanel3);

        jtable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Population", "Standard quota", "Nearest int", "Modified quota", "Final apportionment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable4.setGridColor(new java.awt.Color(0, 153, 153));
        jtable4.setShowVerticalLines(true);
        jtable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jtable4);
        if (jtable4.getColumnModel().getColumnCount() > 0) {
            jtable4.getColumnModel().getColumn(0).setResizable(false);
            jtable4.getColumnModel().getColumn(1).setResizable(false);
            jtable4.getColumnModel().getColumn(2).setResizable(false);
            jtable4.getColumnModel().getColumn(3).setResizable(false);
            jtable4.getColumnModel().getColumn(4).setResizable(false);
            jtable4.getColumnModel().getColumn(5).setResizable(false);
        }

        add3.setText("Add row");
        add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add3ActionPerformed(evt);
            }
        });

        delete3.setText("Delete row");
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });

        reset3.setText("Reset");
        reset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset3ActionPerformed(evt);
            }
        });

        calculate3.setText("Calculate");
        calculate3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate3ActionPerformed(evt);
            }
        });

        edit3.setText("Edit");
        edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
            .addComponent(jScrollPane4)
        );

        jTabbedPane1.addTab("Webster's method", jPanel4);

        jtable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Population", "Standard quota", "LQ", "UQ", "GM", "Apportionment", "Modified quota", "LQ", "UQ", "GM", "Final apportionment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtable5.setGridColor(new java.awt.Color(0, 153, 153));
        jtable5.setShowVerticalLines(true);
        jtable5.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(jtable5);
        if (jtable5.getColumnModel().getColumnCount() > 0) {
            jtable5.getColumnModel().getColumn(0).setResizable(false);
            jtable5.getColumnModel().getColumn(1).setResizable(false);
            jtable5.getColumnModel().getColumn(2).setResizable(false);
            jtable5.getColumnModel().getColumn(3).setResizable(false);
            jtable5.getColumnModel().getColumn(4).setResizable(false);
            jtable5.getColumnModel().getColumn(5).setResizable(false);
            jtable5.getColumnModel().getColumn(6).setResizable(false);
            jtable5.getColumnModel().getColumn(7).setResizable(false);
            jtable5.getColumnModel().getColumn(8).setResizable(false);
            jtable5.getColumnModel().getColumn(9).setResizable(false);
            jtable5.getColumnModel().getColumn(10).setResizable(false);
            jtable5.getColumnModel().getColumn(11).setResizable(false);
        }

        calculate4.setText("Calculate");
        calculate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate4ActionPerformed(evt);
            }
        });

        reset4.setText("Reset");
        reset4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset4ActionPerformed(evt);
            }
        });

        delete4.setText("Delete row");
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });

        add4.setText("Add row");
        add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add4ActionPerformed(evt);
            }
        });

        edit4.setText("Edit");
        edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reset4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculate4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(add4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reset4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculate4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(edit4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 191, Short.MAX_VALUE))
            .addComponent(jScrollPane5)
        );

        jTabbedPane1.addTab("Huntington - Mill method", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 136, 1570, 700));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Apportionment");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 957, 65));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Total number of resources to be allocated:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 425, 53));

        resources.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        getContentPane().add(resources, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 526, 53));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
double divisor = 0;
    double standarddivisor = 0;
    String res;
    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_addActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.setRowCount(0);
        enablecomponents(jtable1, add, delete, calculate);
        resources.setText("");
        edit.setEnabled(false);
    }//GEN-LAST:event_resetActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        int selectedRow = jtable1.getSelectedRow();

// Check if a row is selected
        if (selectedRow != -1) {
            model.removeRow(selectedRow); // Remove the selected row
        } else {
            // If no row is selected, delete the last row
            int lastRow = jtable1.getRowCount() - 1;
            if (lastRow >= 0) {
                model.removeRow(lastRow);
            } else {
                JOptionPane.showMessageDialog(this, "The table is empty!");
            }
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // Disable buttons and table during calculation
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        disablecomponents(jtable1, add, delete, calculate);
        // Force commit any changes in the 'resources' text field before calculation
        if (resources != null) {
            resources.transferFocus(); // Forces the text field to commit the value
        }

        // Validate and parse the 'resources' value
        double totres = parseAndValidateResources();
        if (totres == -1) {
            // If parsing failed, return early and don't proceed with calculation
            enablecomponents(jtable1, add, delete, calculate); // Re-enable components
            return;
        }

        double total = performtotal(jtable1, 1); // Call the method to get the total
        if (total == -1) {
            enablecomponents(jtable1, add, delete, calculate); // Re-enable components
            return;
        }

        divisor = total / totres;
        // Iterate through each row to calculate and update the Standard Quota column

        updateStandardQuota(jtable1, divisor, 2);
        updateLQ(jtable1, 2, 3);
        double totstand = performtotal(jtable1, 2);
        double totLQ = performtotal(jtable1, 3);
        double extra = totres - totLQ;
        distributeExtraSeats(model, extra);
        hamiltonapportion(model);

        model.addRow(new Object[]{"TOTAL", total, totstand, totLQ, extra, totres}); // Add the total row
        edit.setEnabled(true);
    }//GEN-LAST:event_calculateActionPerformed

    private void calculate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate1ActionPerformed
        // Disable buttons and table during calculation
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        disablecomponents(jtable2, add1, delete1, calculate1);
        // Force commit any changes in the 'resources' text field before calculation
        if (resources != null) {
            resources.transferFocus(); // Forces the text field to commit the value
        }

        // Validate and parse the 'resources' value
        double totres = parseAndValidateResources();
        if (totres == -1) {
            // If parsing failed, return early and don't proceed with calculation
            enablecomponents(jtable2, add1, delete1, calculate1); // Re-enable components
            return;
        }

        double total = performtotal(jtable2, 1); // Call the method to get the total
        if (total == -1) {
            enablecomponents(jtable2, add1, delete1, calculate1); // Re-enable components
            return;
        }

        divisor = total / totres;

        updateStandardQuota(jtable2, divisor, 2);
        updateLQ(jtable2, 2, 3);
        double totstand = performtotal(jtable2, 2);
        double totLQ = performtotal(jtable2, 3);
        if (totLQ == totres) {
            updateLQ(jtable2, 2, 5);
            nothing(jtable2, 4);
            model.addRow(new Object[]{"TOTAL", total, totstand, totLQ, "-", totLQ}); // Add the total row
        } else {
            double totmod = 0;
            double totmodLQ = 0;
            double goalLQ = totres;
            do {
                divisor = total / (totres + .005);
                totres = totres + .005;
                updateStandardQuota(jtable2, divisor, 4);
                updateLQ(jtable2, 4, 5);
                totmod = performtotal(jtable2, 4);
                totmodLQ = performtotal(jtable2, 5);;
            } while (totmodLQ != goalLQ);
            model.addRow(new Object[]{"TOTAL", total, totstand, totLQ, totmod, totmodLQ}); // Add the total row

        }
        edit1.setEnabled(true);
    }//GEN-LAST:event_calculate1ActionPerformed

    private void reset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        model.setRowCount(0);
        enablecomponents(jtable2, add1, delete1, calculate1);
        resources.setText("");
        edit1.setEnabled(false);
    }//GEN-LAST:event_reset1ActionPerformed

    private void delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        int selectedRow = jtable2.getSelectedRow();

// Check if a row is selected
        if (selectedRow != -1) {
            model.removeRow(selectedRow); // Remove the selected row
        } else {
            // If no row is selected, delete the last row
            int lastRow = jtable2.getRowCount() - 1;
            if (lastRow >= 0) {
                model.removeRow(lastRow);
            } else {
                JOptionPane.showMessageDialog(this, "The table is empty!");
            }
        }
    }//GEN-LAST:event_delete1ActionPerformed

    private void add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_add1ActionPerformed

    private void calculate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate2ActionPerformed
        // Disable buttons and table during calculation
        DefaultTableModel model = (DefaultTableModel) jtable3.getModel();
        disablecomponents(jtable3, add2, delete2, calculate2);
        // Force commit any changes in the 'resources' text field before calculation
        if (resources != null) {
            resources.transferFocus(); // Forces the text field to commit the value
        }

        // Validate and parse the 'resources' value
        double totres = parseAndValidateResources();
        if (totres == -1) {
            // If parsing failed, return early and don't proceed with calculation
            enablecomponents(jtable3, add2, delete2, calculate2); // Re-enable components
            return;
        }

        double total = performtotal(jtable3, 1); // Call the method to get the total
        if (total == -1) {
            enablecomponents(jtable3, add2, delete2, calculate2); // Re-enable components
            return;
        }

        divisor = total / totres;

        updateStandardQuota(jtable3, divisor, 2);
        updateUQ(jtable3, 2, 3);
        double totstand = performtotal(jtable3, 2);
        double totUQ = performtotal(jtable3, 3);
        if (totUQ == totres) {
            updateUQ(jtable3, 2, 5);
            nothing(jtable3, 4);
            model.addRow(new Object[]{"TOTAL", total, totstand, totUQ, "-", totUQ}); // Add the total row
        } else {
            double totmod = 0;
            double totmodUQ = 0;
            double goalUQ = totres;
            do {
                divisor = total / (totres - .005);
                totres = totres - .005;
                updateStandardQuota(jtable3, divisor, 4);
                updateUQ(jtable3, 4, 5);
                totmod = performtotal(jtable3, 4);
                totmodUQ = performtotal(jtable3, 5);;
            } while (totmodUQ != goalUQ);
            model.addRow(new Object[]{"TOTAL", total, totstand, totUQ, totmod, totmodUQ}); // Add the total row

        }
        edit2.setEnabled(false);
    }//GEN-LAST:event_calculate2ActionPerformed

    private void reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable3.getModel();
        model.setRowCount(0);
        enablecomponents(jtable3, add2, delete2, calculate2);
        resources.setText("");
        edit2.setEnabled(false);
    }//GEN-LAST:event_reset2ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable3.getModel();
        int selectedRow = jtable3.getSelectedRow();

// Check if a row is selected
        if (selectedRow != -1) {
            model.removeRow(selectedRow); // Remove the selected row
        } else {
            // If no row is selected, delete the last row
            int lastRow = jtable3.getRowCount() - 1;
            if (lastRow >= 0) {
                model.removeRow(lastRow);
            } else {
                JOptionPane.showMessageDialog(this, "The table is empty!");
            }
        }
    }//GEN-LAST:event_delete2ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable3.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_add2ActionPerformed

    private void add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable4.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_add3ActionPerformed

    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable4.getModel();
        int selectedRow = jtable4.getSelectedRow();

// Check if a row is selected
        if (selectedRow != -1) {
            model.removeRow(selectedRow); // Remove the selected row
        } else {
            // If no row is selected, delete the last row
            int lastRow = jtable4.getRowCount() - 1;
            if (lastRow >= 0) {
                model.removeRow(lastRow);
            } else {
                JOptionPane.showMessageDialog(this, "The table is empty!");
            }
        }
    }//GEN-LAST:event_delete3ActionPerformed

    private void reset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable4.getModel();
        model.setRowCount(0);
        enablecomponents(jtable4, add3, delete3, calculate3);
        resources.setText("");
        edit3.setEnabled(false);
    }//GEN-LAST:event_reset3ActionPerformed

    private void calculate3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate3ActionPerformed
        // Disable buttons and table during calculation
        DefaultTableModel model = (DefaultTableModel) jtable4.getModel();
        disablecomponents(jtable4, add3, delete3, calculate3);
        // Force commit any changes in the 'resources' text field before calculation
        if (resources != null) {
            resources.transferFocus(); // Forces the text field to commit the value
        }

        // Validate and parse the 'resources' value
        double totres = parseAndValidateResources();
        if (totres == -1) {
            // If parsing failed, return early and don't proceed with calculation
            enablecomponents(jtable4, add3, delete3, calculate3); // Re-enable components
            return;
        }

        double total = performtotal(jtable4, 1); // Call the method to get the total
        if (total == -1) {
            enablecomponents(jtable4, add3, delete3, calculate3); // Re-enable components
            return;
        }

        divisor = total / totres;

        updateStandardQuota(jtable4, divisor, 2);
        nearestint(jtable4, 2, 3);
        double totstand = performtotal(jtable4, 2);
        double totNI = performtotal(jtable4, 3);
        if (totNI == totres) {
            updateStandardQuota(jtable4, divisor, 4);
            nearestint(jtable4, 2, 5);
            nothing(jtable4, 4);
            model.addRow(new Object[]{"TOTAL", total, totstand, totNI, "-", totNI}); // Add the total row
        } else {
            double totmod = 0;
            double totmodNI = 0;
            double goalNI = totres;
            do {
                if (totNI > totres) {
                    divisor = total / (totres - .005);
                    totres = totres - .005;
                    updateStandardQuota(jtable4, divisor, 4);
                    nearestint(jtable4, 4, 5);
                    totmod = performtotal(jtable4, 4);
                    totmodNI = performtotal(jtable4, 5);
                } else {
                    divisor = total / (totres + .005);
                    totres = totres + .005;
                    updateStandardQuota(jtable4, divisor, 4);
                    nearestint(jtable4, 4, 5);
                    totmod = performtotal(jtable4, 4);
                    totmodNI = performtotal(jtable4, 5);
                }
            } while (totmodNI != goalNI);
            model.addRow(new Object[]{"TOTAL", total, totstand, totNI, totmod, totmodNI}); // Add the total row

        }
        edit3.setEnabled(true);
    }//GEN-LAST:event_calculate3ActionPerformed

    private void calculate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate4ActionPerformed
        // Disable buttons and table during calculation
        DefaultTableModel model = (DefaultTableModel) jtable5.getModel();
        disablecomponents(jtable5, add4, delete4, calculate4);
        // Force commit any changes in the 'resources' text field before calculation
        if (resources != null) {
            resources.transferFocus(); // Forces the text field to commit the value
        }

        // Validate and parse the 'resources' value
        double totres = parseAndValidateResources();
        if (totres == -1) {
            // If parsing failed, return early and don't proceed with calculation
            enablecomponents(jtable5, add4, delete4, calculate4); // Re-enable components
            return;
        }

        double total = performtotal(jtable5, 1); // Call the method to get the total
        if (total == -1) {
            enablecomponents(jtable5, add4, delete4, calculate4); // Re-enable components
            return;
        }

        divisor = total / totres;

        updateStandardQuota(jtable5, divisor, 2);
        updateLQ(jtable5, 2, 3);
        updateUQ(jtable5, 2, 4);
        GM(jtable5, 3, 4, 5);
        huntingtonhillapportion(jtable5, 3, 4, 2, 5, 6);
        double totstand = performtotal(jtable5, 2);
        double totLQ = performtotal(jtable5, 3);
        double totUQ = performtotal(jtable5, 4);
        double totGM = performtotal(jtable5, 5);
        double hunt = performtotal(jtable5, 6);
        if (hunt == totres) {
            updateStandardQuota(jtable5, divisor, 7);
            updateLQ(jtable5, 2, 8);
            updateUQ(jtable5, 2, 9);
            GM(jtable5, 3, 4, 10);
            nothing(jtable5, 7);
            nothing(jtable5, 8);
            nothing(jtable5, 9);
            nothing(jtable5, 10);
            huntingtonhillapportion(jtable5, 3, 4, 2, 5, 11);
            model.addRow(new Object[]{"TOTAL", total, totstand, totLQ, totUQ, totGM, hunt, "-", "-", "-", "-", hunt});
        } else {
            double totmod = 0;
            double tothunt = 0;
            double goalhunt = totres;
            double totmodlq = 0;
            double totmoduq = 0;
            double totmodgm = 0;
            do {
                if (hunt > totres) {
                    divisor = total / (totres - .005);
                    totres = totres - .005;
                    updateStandardQuota(jtable5, divisor, 7);
                    updateLQ(jtable5, 7, 8);
                    updateUQ(jtable5, 7, 9);
                    GM(jtable5, 8, 9, 10);
                    huntingtonhillapportion(jtable5, 8, 9, 7, 10, 11);
                    totmod = performtotal(jtable5, 7);
                    totmodlq = performtotal(jtable5, 8);
                    totmoduq = performtotal(jtable5, 9);
                    totmodgm = performtotal(jtable5, 10);
                    tothunt = performtotal(jtable5, 11);
                } else {
                    divisor = total / (totres + .005);
                    totres = totres + .005;
                    updateStandardQuota(jtable5, divisor, 7);
                    updateLQ(jtable5, 7, 8);
                    updateUQ(jtable5, 7, 9);
                    GM(jtable5, 8, 9, 10);
                    huntingtonhillapportion(jtable5, 8, 9, 7, 10, 11);
                    totmod = performtotal(jtable5, 7);
                    totmodlq = performtotal(jtable5, 8);
                    totmoduq = performtotal(jtable5, 9);
                    totmodgm = performtotal(jtable5, 10);
                    tothunt = performtotal(jtable5, 11);
                }
            } while (tothunt != goalhunt);
            model.addRow(new Object[]{"TOTAL", total, totstand, totLQ, totUQ, totGM, hunt, totmod, totmodlq, totmoduq, totmodgm, tothunt});
        }
        edit4.setEnabled(true);

    }//GEN-LAST:event_calculate4ActionPerformed

    private void reset4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable5.getModel();
        model.setRowCount(0);
        enablecomponents(jtable5, add4, delete4, calculate4);
        resources.setText("");
        edit4.setEnabled(false);
    }//GEN-LAST:event_reset4ActionPerformed

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable5.getModel();
        int selectedRow = jtable5.getSelectedRow();

// Check if a row is selected
        if (selectedRow != -1) {
            model.removeRow(selectedRow); // Remove the selected row
        } else {
            // If no row is selected, delete the last row
            int lastRow = jtable5.getRowCount() - 1;
            if (lastRow >= 0) {
                model.removeRow(lastRow);
            } else {
                JOptionPane.showMessageDialog(this, "The table is empty!");
            }
        }
    }//GEN-LAST:event_delete4ActionPerformed

    private void add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable5.getModel();
        model.addRow(new Object[]{});
    }//GEN-LAST:event_add4ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable1.getModel();
        model.setRowCount(model.getRowCount() - 1);
        enablecomponents(jtable1, add, delete, calculate);
        for (int row = 0; row < model.getRowCount(); row++) {
            model.setValueAt("", row, 2);
            model.setValueAt("", row, 3);
            model.setValueAt("", row, 4);
            model.setValueAt("", row, 5);
        }
        edit.setEnabled(false);
    }//GEN-LAST:event_editActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable2.getModel();
        model.setRowCount(model.getRowCount() - 1);
        enablecomponents(jtable2, add1, delete1, calculate1);
        for (int row = 0; row < model.getRowCount(); row++) {
            model.setValueAt("", row, 2);
            model.setValueAt("", row, 3);
            model.setValueAt("", row, 4);
            model.setValueAt("", row, 5);
        }
        edit1.setEnabled(false);
    }//GEN-LAST:event_edit1ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable3.getModel();
        model.setRowCount(model.getRowCount() - 1);
        enablecomponents(jtable3, add2, delete2, calculate2);
        for (int row = 0; row < model.getRowCount(); row++) {
            model.setValueAt("", row, 2);
            model.setValueAt("", row, 3);
            model.setValueAt("", row, 4);
            model.setValueAt("", row, 5);
        }
        edit2.setEnabled(false);
    }//GEN-LAST:event_edit2ActionPerformed

    private void edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit3ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable4.getModel();
        model.setRowCount(model.getRowCount() - 1);
        enablecomponents(jtable4, add3, delete3, calculate3);
        for (int row = 0; row < model.getRowCount(); row++) {
            model.setValueAt("", row, 2);
            model.setValueAt("", row, 3);
            model.setValueAt("", row, 4);
            model.setValueAt("", row, 5);
        }
        edit3.setEnabled(false);
    }//GEN-LAST:event_edit3ActionPerformed

    private void edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit4ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jtable5.getModel();
        model.setRowCount(model.getRowCount() - 1);
        enablecomponents(jtable5, add4, delete4, calculate4);
        for (int row = 0; row < model.getRowCount(); row++) {
            model.setValueAt("", row, 2);
            model.setValueAt("", row, 3);
            model.setValueAt("", row, 4);
            model.setValueAt("", row, 5);
            model.setValueAt("", row, 6);
            model.setValueAt("", row, 7);
            model.setValueAt("", row, 8);
            model.setValueAt("", row, 9);
            model.setValueAt("", row, 10);
            model.setValueAt("", row, 11);
        }
        edit4.setEnabled(false);
    }//GEN-LAST:event_edit4ActionPerformed
    private double performtotal(JTable table, int columnIndex) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        // Force commit changes for the last row (if any editing is in progress)
        int lastRow = model.getRowCount() - 1;
        if (lastRow >= 0) {
            for (int col = 0; col < model.getColumnCount(); col++) {
                table.editCellAt(lastRow, col); // This uses the JTable for UI interaction
                if (table.getCellEditor() != null) {
                    table.getCellEditor().stopCellEditing();
                }
            }
        }

        BigDecimal columnTotal = BigDecimal.ZERO; // Initialize total as 0

        // Iterate over all rows to validate and sum the values in the specified column
        for (int row = 0; row < model.getRowCount(); row++) {
            Object cellValue = model.getValueAt(row, columnIndex); // Get value from the target column
            if (cellValue != null) {
                try {
                    BigDecimal numericValue = new BigDecimal(cellValue.toString()); // Convert to BigDecimal

                    // Validate that the value is >= 0
                    if (numericValue.compareTo(BigDecimal.ZERO) < 0) {
                        JOptionPane.showMessageDialog(null,
                                "Negative value found at row " + (row + 1) + ": " + numericValue,
                                "Invalid Input", JOptionPane.ERROR_MESSAGE);
                        return -1; // Signal an error
                    }

                    columnTotal = columnTotal.add(numericValue); // Add value to the total
                } catch (NumberFormatException | NullPointerException e) {
                    JOptionPane.showMessageDialog(null,
                            "Non-numeric value found at row " + (row + 1) + ": " + cellValue,
                            "Invalid Input", JOptionPane.ERROR_MESSAGE);
                    return -1; // Signal an error
                }
            } else {
                // Handle empty value (null)
                JOptionPane.showMessageDialog(null,
                        "Empty value at row " + (row + 1) + ". Please enter a valid number.",
                        "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return -1; // Signal an error
            }
        }

        // Return the total as a double, rounded to 2 decimal places
        return columnTotal.setScale(2, RoundingMode.HALF_UP).doubleValue();
    }

    private void disablecomponents(JTable table, JButton addButton, JButton deleteButton, JButton calculateButton) {
        addButton.setEnabled(false);
        deleteButton.setEnabled(false);
        table.setEnabled(false);
        calculateButton.setEnabled(false);
        resources.setEnabled(false);
    }

    private void enablecomponents(JTable table, JButton addButton, JButton deleteButton, JButton calculateButton) {
        addButton.setEnabled(true);
        deleteButton.setEnabled(true);
        table.setEnabled(true);
        calculateButton.setEnabled(true);
        resources.setEnabled(true);
    }

    private double parseAndValidateResources() {
        try {
            res = resources.getText().trim(); // Get and trim the text from 'resources'

            // Check if the input is empty
            if (res.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please enter a value in the resources field.",
                        "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return -1; // Return -1 to signal an error
            }

            // Try to parse it to a double
            double totres = Double.parseDouble(res);

            // Check if the value is negative
            if (totres < 0) {
                JOptionPane.showMessageDialog(null, "Negative values are not allowed in the resources field.",
                        "Invalid Input", JOptionPane.ERROR_MESSAGE);
                return -1; // Return -1 to signal an error
            }

            return totres; // Return the valid parsed value
        } catch (NumberFormatException e) {
            // Handle invalid number input
            JOptionPane.showMessageDialog(null, "Please enter a valid number in the resources field.",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return -1; // Return -1 to signal an error
        }
    }

    private void updateStandardQuota(JTable table, double divisor, int s) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            // Fetch the population from the table 
            Object populationValue = model.getValueAt(row, 1); // Population column (index 1)
            double population = Double.parseDouble(populationValue.toString());
            double standardQuota = population / divisor; // Standard Quota calculation
            BigDecimal roundedQuota = BigDecimal.valueOf(standardQuota).setScale(2, RoundingMode.HALF_UP);

            model.setValueAt(roundedQuota, row, s); // Set the value in the Standard Quota column
        }
    }

    private void updateLQ(JTable table, int g, int s) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            Object standardQuotaValue = model.getValueAt(row, g); // Standard Quota column (index 2)
            double standardQuota = Double.parseDouble(standardQuotaValue.toString());
            double lowerQuota = Math.floor(standardQuota);
            model.setValueAt(lowerQuota, row, s);
        }
    }

    private void updateUQ(JTable table, int g, int s) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            Object standardQuotaValue = model.getValueAt(row, g); // Standard Quota column (index 2)
            double standardQuota = Double.parseDouble(standardQuotaValue.toString());
            double upperQuota = Math.ceil(standardQuota);
            model.setValueAt(upperQuota, row, s);
        }
    }

    private void nothing(JTable table, int s) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            model.setValueAt("-", row, s);
        }
    }

    private void nearestint(JTable table, int g, int s) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            Object standardQuotaValue = model.getValueAt(row, g); // Standard Quota column (index g)
            double standardQuota = Double.parseDouble(standardQuotaValue.toString());
            double roundedQuota = Math.round(standardQuota); // Round to the nearest integer
            model.setValueAt(roundedQuota, row, s); // Set the value in the Lower Quota column (index s)
        }
    }

    private void GM(JTable table, int g1, int g2, int s) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            Object lowerQuotaValue = model.getValueAt(row, g1);
            Object upperQuotaValue = model.getValueAt(row, g2);
            double lowerQuota = Double.parseDouble(lowerQuotaValue.toString());
            double upperQuota = Double.parseDouble(upperQuotaValue.toString());
            double geometricmean = Math.sqrt(lowerQuota * upperQuota);
            BigDecimal roundedQuota = BigDecimal.valueOf(geometricmean).setScale(2, RoundingMode.HALF_UP);
            model.setValueAt(roundedQuota, row, s); // Set the value in the Lower Quota column (index s)
        }
    }

    private void huntingtonhillapportion(JTable table, int lq, int uq, int g1, int g2, int s) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
            Object lowerQuotaValue = model.getValueAt(row, lq);
            Object upperQuotaValue = model.getValueAt(row, uq);
            Object standard = model.getValueAt(row, g1);
            Object geometric = model.getValueAt(row, g2);
            double SQ = Double.parseDouble(standard.toString());
            double GM = Double.parseDouble(geometric.toString());
            double lowerQuota = Double.parseDouble(lowerQuotaValue.toString());
            double upperQuota = Double.parseDouble(upperQuotaValue.toString());
            if (SQ < GM) {
                model.setValueAt(lowerQuota, row, s);
            } else {
                model.setValueAt(upperQuota, row, s);
            }
        }
    }

    private void distributeExtraSeats(DefaultTableModel model, double extrares) {
        int rowCount = model.getRowCount();
        double[] remainders = new double[rowCount];
        int[] extraSeatDistribution = new int[rowCount];

        // Calculate remainders for each row
        for (int row = 0; row < rowCount; row++) {
            double standardQuota = Double.parseDouble(model.getValueAt(row, 2).toString());
            double lowerQuota = Math.floor(standardQuota);
            remainders[row] = standardQuota - lowerQuota;
        }

        // Distribute extra seats based on remainders and tie-break by population
        while (extrares > 0) {
            int maxIndex = -1;
            double maxRemainder = -1;
            int maxPopulation = -1;

            // Find the row with the maximum remainder
            for (int row = 0; row < rowCount; row++) {
                if (remainders[row] > maxRemainder
                        || (remainders[row] == maxRemainder
                        && Integer.parseInt(model.getValueAt(row, 1).toString()) > maxPopulation)) {

                    maxRemainder = remainders[row];
                    maxPopulation = Integer.parseInt(model.getValueAt(row, 1).toString());
                    maxIndex = row;
                }
            }

            if (maxIndex >= 0) {
                extraSeatDistribution[maxIndex]++;
                remainders[maxIndex] = -1;  // Mark as used
                extrares--;
            } else {
                break;
            }
        }

        // Update the "Extra Seats" column
        for (int row = 0; row < rowCount; row++) {
            model.setValueAt(extraSeatDistribution[row], row, 4);
        }
    }

    private void hamiltonapportion(DefaultTableModel model) {
        for (int row = 0; row < model.getRowCount(); row++) {

            Object LQ1 = model.getValueAt(row, 3);
            Object Extrar = model.getValueAt(row, 4);
            double LQ2 = Double.parseDouble(LQ1.toString());
            double Extrarr = Double.parseDouble(Extrar.toString());
            double Finalapp = LQ2 + Extrarr;

            model.setValueAt(Finalapp, row, 5); // Set the value in the Standard Quota column

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(idk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(idk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(idk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(idk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new idk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton add1;
    private javax.swing.JButton add2;
    private javax.swing.JButton add3;
    private javax.swing.JButton add4;
    private javax.swing.JButton calculate;
    private javax.swing.JButton calculate1;
    private javax.swing.JButton calculate2;
    private javax.swing.JButton calculate3;
    private javax.swing.JButton calculate4;
    private javax.swing.JButton delete;
    private javax.swing.JButton delete1;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JButton delete4;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit1;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit3;
    private javax.swing.JButton edit4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jtable1;
    private javax.swing.JTable jtable2;
    private javax.swing.JTable jtable3;
    private javax.swing.JTable jtable4;
    private javax.swing.JTable jtable5;
    private javax.swing.JButton reset;
    private javax.swing.JButton reset1;
    private javax.swing.JButton reset2;
    private javax.swing.JButton reset3;
    private javax.swing.JButton reset4;
    private javax.swing.JTextField resources;
    // End of variables declaration//GEN-END:variables
}
